#!/usr/bin/python

# to generate two binaries, use:
# ln -s base base58
# ln -s base base94

import sys
import os
import unicodedata

alphabet = ''.join(chr(i) for i in range(0x1F300, 0x1F700))
BASE = len(alphabet)

arg = os.path.basename(sys.argv[0])
if arg == "base94":
    BASE = 94
    alphabet = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~"
elif arg == "base58":
    BASE = 58
    alphabet = "123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

def encode(num, alphabet):
    result = ''
    while num > 0:
        result = alphabet[num % BASE] + result
        num //= BASE
    return result

def decode(encoded, alphabet):
    result = 0
    for char in encoded:
        result = result * BASE + alphabet.index(char)
    return result

def string_to_hex(s):
    return s.hex()

def hex_to_decimal(hex_str):
    return int(hex_str, 16)

if len(sys.argv) > 1 and sys.argv[1] == "-d":
    try:
        while True:
            encoded_data = sys.stdin.readline().strip()
            if not encoded_data:
                break
            decimal = decode(encoded_data, alphabet)
            hex_string = hex(decimal)[2:]
            if len(hex_string) % 2 == 1:
                hex_string = '0' + hex_string
            binary_data = bytes.fromhex(hex_string)
            sys.stdout.buffer.write(binary_data)
    except EOFError:
        pass
else:
    try:
        while True:
            binary_data = sys.stdin.buffer.read()
            if not binary_data:
                break
            hex_string = string_to_hex(binary_data)
            decimal = hex_to_decimal(hex_string)
            encoded = encode(decimal, alphabet)
            print(encoded)
    except EOFError:
        pass
