#!/usr/bin/fish

switch "$argv[1]"
	case "open"
	    read -s key
	    touch /tmp/container_key_"$USER"
	    chmod 600 /tmp/container_key_"$USER"
	    echo -n "$key" > "/tmp/container_key_$USER"
		touch /tmp/container_"$USER"
		chmod 600 /tmp/container_"$USER"
		scrypt dec --passphrase file:"/tmp/container_key_$USER" "$argv[2]" > /tmp/container_"$USER" || exit 1
		$EDITOR /tmp/container_"$USER"
		cp "$argv[2]" "$argv[2]".bkup
		scrypt enc --passphrase file:"/tmp/container_key_$USER" --logN 20 -r4 -p2 /tmp/container_"$USER" > "$argv[2]" && \
		rm "$argv[2]".bkup
	case "create"
	    test -e "$argv[2]" && begin
	        echo "file already exists"
	    end || scrypt enc --logN 20 -r4 -p2 /dev/null > "$argv[2]"
end
