#!/usr/bin/fish

function message
    switch $argv[2]
        case "1" 
            tput bold; echo -n "-> "; tput setaf 1; echo "$argv[1]"; tput sgr0
        case "2" 
            tput setaf 63; echo -n " * "; tput setaf 12; echo "$argv[1]"; tput sgr0
        case "3" 
            tput setaf 8; echo -n " * "; tput setaf 13; echo "$argv[1]"; tput sgr0
        case '*' 
            tput setaf 39; echo -n "-> "; tput setaf 25; echo "$argv[1]"; tput sgr0
    end
end

if test (count $argv) -eq 1
    set device $argv[1]
    set lol (basename $device)

    if not echo $device | grep "/dev/"
        if echo $device | grep -qE '^sd[a-z].*$'
            message "warning: entire location detected (use properly!, e.g. /dev/sda, not sda)" 3
            set device /dev/$device
            message "defaulting to $device"
        else
            message "finding a file with that name... (make sure this file exists)"
            exit 1
        end
    end

    if sudo cryptsetup isLuks $device >/dev/null
        sudo cryptsetup luksOpen $device $lol || exit 1
        sudo mount --mkdir /dev/mapper/$lol /mnt/$lol || exit 1
        message "mounted cryptfs at /mnt/$lol"
    else
        sudo mkdir /mnt/$lol 2>/dev/null
        sudo mount $device /mnt/$lol || exit 1
        message "mounted at /mnt/$lol"
    end
end
