#!/usr/bin/bash

filename="$HOME/Desktop/$(date -R)"

maim -u "$filename"
feh -x -F "$filename" &
id=$!
maim -s "$filename"
kill $id

xclip -selection clipboard -t image/png -i "$filename"

avifenc "$filename" "$filename".avif

{ sleep 60; rm "$filename"; } &

dunstify "saved at $HOME/Desktop/$(date -R).png"
