#!/usr/bin/python3

import random,string,sys,requests


def main():
    if len(sys.argv) > 1:
        if sys.argv[1] == "phrase":
            response = requests.get("https://raw.githubusercontent.com/first20hours/google-10000-english/master/google-10000-english.txt")
            words = response.text.splitlines()
            
            random_words = random.sample(words, 6)
            for v in random_words:
                print(v, end=" ")

            print()
            exit()

        if sys.argv[1] == "secure":
            consonants = ['b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'r', 's', 't', 'v', 'y']
            vowels = ['a', 'e', 'i', 'o', 'u']
            
            for i in range(3):
                word = ""
                for i in range(3):
                    word += random.choice(consonants)
                    word += random.choice(vowels)
                    
                print(word, end=" ")
                        
            print()
            
            exit()

        if sys.argv[1] == "emoji":            
            def generate_random_object_emoji():
                emoji = chr(random.randint(0x1F300, 0x1F5FF))
                return emoji
            
            emojis = []
            for _ in range(6):
                random_emoji = generate_random_object_emoji()
                emojis.append(random_emoji)
            
            print(" ".join(emojis))
            exit()
            
    print(''.join(random.choices(string.ascii_lowercase + string.digits, k=int(sys.argv[1]) if len(sys.argv) > 1 else 4)))
    

if __name__ == "__main__":
    main()
