#!/usr/bin/bash

test -z "$1" && {
	echo "USAGE: resize [size in px] INPUT OUTPUT"
	exit 1
}
test -z "$2" && {
	echo "USAGE: resize [size in px] INPUT OUTPUT"
	exit 1
}

size="$1"

test -z "$1" && {
	size=480
}

ffmpeg -i "$2" -vf "scale=-1:$size" "$3"
