#!/bin/bash

gen_name () {
  echo "xclip-$(tr -dc "a-z" </dev/urandom | head -c 10)"
}

_convert () {
  convert "$_where" -resize x170 /tmp/sa_icon.jpg
}

save () {
  where="$savelocation""$filename"
  xclip -selection clipboard -t i
  mage/png -o > $where && \
  avifenc $where $where.avif || { dunstify "error saving pic"; exit 1; }
  # cjxl $where $where.jxl
  rm $where && \
  if [ "$(pwd)" != "$HOME" ]; then
    _where="$(pwd)/$where.avif"
    _convert
  else
    _where=$where.avif
    _convert
  fi
  
  dunstify -i /tmp/sa_icon.jpg "saved at $where.avif"
  rm /tmp/sa_icon.jpg

}

filename=$(gen_name)

if [ "$(pwd)" != "$HOME" ]; then
  while true; do
    test -e "$where" && where=$(gen_name) || break
  done
  savelocation=""
else
  savelocation="$HOME/Desktop/"
fi

save &> /dev/null &

