#!/usr/bin/bash

folder="$HOME/Recordings"

mkdir "$folder"

screen_resolution=$(xrandr | grep '*' | awk '{print $1}')
fps=$(xrandr | grep '*' | awk '{print $2}' | sed 's/[*+]//g' | awk '{ printf "%.0f\n", $1 }')

ffmpeg -f x11grab -s $screen_resolution -r 30 -framerate $fps -i :0.0 -f alsa -i default -q:v 0 "$folder"/"recording$(date -R)".mp4 &
pid=$!

read -sn1 i
sleep 1 
kill -INT $pid

exit 0

