#!/usr/bin/bash

mkdir $HOME/Desktop/Recordings
mkdir $HOME/Desktop/Recordings/screenshot-recordings

counter=1
folder="$HOME/Desktop/Recordings/screenshot-recordings$(date -R)"

mkdir "$folder"

while true; do
    filename="$folder/screenshot_$counter.png"

    scrot -pzq 1 -Z 9 "$filename" || exit 1

    time avifenc "$filename" -o "$folder/screenshot_$counter.avif" || exit 1
    
    rm "$filename" || exit 1

    ((counter++))
    
done
