#!/usr/bin/bash

get_gpu () {
     lspci | grep -i 'VGA' | awk -F': ' '{print $2}' | sed 's/(rev ..)//g' | head -n1 | sed -n 's/.*\[\(.*\)\].*/\1/p'
}

packages="Packages: $(tput sgr0)$(pacman -Qqe | wc -l) / $(pacman -Qq | wc -l)$(tput setaf 39)"
kernel="Kernel: $(tput sgr0)$(uname -r)$(tput setaf 39)"
shell="Shell: $(tput sgr0)$(echo $SHELL)$(tput setaf 39)"
term="Term: $(tput sgr0)$(echo $TERM)$(tput setaf 39)"

ram="RAM: $(tput sgr0)$(free --mega | awk '/^Mem:/ {print $3 "MB" " / " $2 "MB"}') "$(tput setaf 39)""
cpu="CPU: $(tput sgr0)$(echo $(grep -m1 'model name' /proc/cpuinfo | awk -F': ' '{print $2}' | sed 's/with.*$//'))$(tput setaf 39)"
gpu="GPU: $(tput sgr0)$(get_gpu)$(tput setaf 39)"
disk="Disk: $(tput sgr0)$(echo $(df -H | grep " /\b" -v | tail -n1 | awk '{ print $3"/"$2 }'))$(tput setaf 39)"

element[0]=$packages
element[1]=$kernel
element[2]=$shell
element[3]=$term

element[4]=$disk
element[5]=$ram
element[6]=$cpu
element[7]=$gpu

test -z "$(get_gpu)" && element[7]=""

echo -e "$(tput setaf 39)
     _             _
    / \   _ __ ___| |__       ${element[0]}
   / _ \ | '__/ __| '_ \\      ${element[1]}
  / ___ \| | | (__| | | |     ${element[2]}
 /_/   \_\_|  \___|_| |_|     ${element[3]}
  _     _                     
 | |   (_)_ __  _   ___  __   ${element[4]}
 | |   | | '_ \| | | \ \/ /   ${element[5]}
 | |___| | | | | |_| |>  <    ${element[6]}
 |_____|_|_| |_|\____/_/\_\\   ${element[7]}

$(tput sgr0)                              $(for c in $(seq 1 6); do tput setaf $c; echo -n "██"; done; tput sgr0; echo)
"

#
#  sfetch 1.1.1
#  created by clyde, on 18 feb 2024 at 16:39 CET
#

# clyde, on 3 mar 2024 at 15:33 CET 
# 1.0.2 patch notes: added the "Disk" line

# clyde, on 12 mar 2024 at 08:33 CET
# 1.0.3 patch notes: made the code cleaner with variables

# clyde, on 25 mar 2024 23:49 CET
# 1.1 patch notes: created more extensibility with $_1, $_2, etc.

# clyde, on 3 apr 2024 09:03 CEST (time change)
# 1.1.1 patch notes: added colors at the bottom
