#!/usr/bin/bash

cd $HOME/Desktop || exit 1
if [ "$(pwd)" != "$HOME/Desktop" ]; then
    echo "current directory is not equal to \$HOME/Desktop"
    exit 1
fi
tar -rf desktop.tar * || exit 1
if [ -e "desktop.tar" ]; then
    find . ! -name "desktop.tar" -type f -delete
    find . ! -name "desktop.tar" -type d -delete
else
    echo "Error: 'desktop.tar' not found."
fi
