#!/usr/bin/bash
 
current_day=$(date +"%-e")

cal_output=$(cal -n2 | sed -E "s/\b$current_day\b/$current_day*/; s/\* /*/" | sed '0,/\*/s/\*/ /' |sed 's/^/    /')

notify-send "
    $(date +"%a, %d %b %Y %T %Z")
    "
