#!/usr/bin/bash
 
current_day=$(date +"%-e")

cal_output=$(cal | sed -E "s/\b$current_day\b/$current_day*/; s/\* /*/" | sed '0,/\*/s/\*/ /' |sed 's/^/    /')

notify-send "$cal_output
    $(date +"%d/%m/%y %T %Z")"
