#!/usr/bin/bash

echo -n "are you sure? "
read -r yn </dev/tty

if [ "$yn" = "y" ] || [ "$yn" = "Y" ] || [ "$yn" = "yes" ]; then
    curl -F 'file=@-' -F secret= 0x0.st
else
    echo "operation cancelled"
fi
