#!/usr/bin/bash

test -z $1 && {
	e=$(gpg -c --pinentry-mode loopback | base64 | curl -F 'file=@-' -Fsecret= 0x0.st | sed 's/http/https/g') 
	echo "$e"
	echo "$e" | xclip -sel c
} || {
	echo "pipe it"
}
