#!/bin/bash
test -n "$1" || { echo "no input provided"; exit 1; }

echo "enter the password"
read -s password
echo "trying to decrypt..."

salt=$(head -n1 "$1" | tr -d '\n')

hashed_password=$(echo -n "$password" | argon2 "$salt" -id -t 2 -m 21 -p 4 | grep Hash | rev | cut -b1-64 | rev)

tmp_file=/tmp/e2
tail -n +2 "$1" > /tmp/e2
openssl enc -d -aes-256-cbc -pbkdf2 -iter 1000000 -salt -k "$hashed_password" -in $tmp_file
