#!/bin/bash
test -n "$1" || { echo "no input provided"; exit 1; }

echo "enter the password"
read -s password
echo "loading the heavy cavalry..."

salt=$(openssl rand 12 | base64)

hashed_password=$(echo -n "$password" | argon2 "$salt" -id -t 2 -m 21 -p 4 | grep Hash | rev | cut -b1-64 | rev)

echo "$salt" > "$1".e2
openssl enc -aes-256-cbc -pbkdf2 -iter 1000000 -salt -in "$1" -k "$hashed_password" >> "$1".e2
