#!/bin/bash

gen_name () {
  echo "xclip-$(tr -dc "a-z" </dev/urandom | head -c 10)"
}

_convert () {
  convert "$_where" -resize x100 /tmp/sa_icon.jpg
}

save () {
  where="$savelocation""$filename"
  xclip -selection clipboard -t image/jpeg -o > $where && \
  cjxl -e 9 --lossless_jpeg=1 $where $where.jxl
  rm $where && \
  if [ "$(pwd)" != "$HOME" ]; then
    _where="$(pwd)/$where.jxl"
    _convert
  else
    _where=$where.jxl
    _convert
  fi
  notify-send -i /tmp/sa_icon.jpg "saved at $where.jxl"
}

filename=$(gen_name)

if [ "$(pwd)" != "$HOME" ]; then
  while true; do
    test -e "$where" && where=$(gen_name) || break
  done
  savelocation=""
else
  savelocation="$HOME/Desktop/"
fi

save &> /dev/null &

