#!/usr/bin/bash

screen_resolution=$(xrandr | grep '*' | awk '{print $1}')
fps=$(xrandr | grep '*' | awk '{print $2}' | sed 's/[*+]//g' | awk '{ printf "%.0f\n", $1 }')

name="$(date +"%s%N")"

if echo "$1" | grep "-"; then
	if echo "$1" | grep "b"; then
		name="$(date +"%s%N" | base32)"
		ffmpeg -f alsa -i default -q:a 0 "$name".mp3 &
	fi
	if echo "$1" | grep "a"; then
		ffmpeg -f alsa -i default -q:a 0 "$name".mp3 &
	fi
else
	ffmpeg -f x11grab -s $screen_resolution -r 30 -framerate $fps -i :0.0 -f alsa -i default -q:v 0 "$name".mp4 &
fi

pid=$!

read -sn1 i
sleep 1 
kill -INT $pid

exit 0

